### ISSUE TITLE
Output with defining SNPs

### ISSUE THREAD

**Issue by nuin** [MEEIBioinformaticsCenter/phy-mer#1]
Not exactly an issue, but a question: are the polymorphisms output when the --def-snps option is used are only the polymorphisms that define the resulting haplogroup, or all SNPs found on the particular genome?

**Comment by danielnavarrogomez** [comment]
Hello,

Since Phy-Mer doesn't use a reference sequence, is not able to "call" snps. 

Answering your question, the polymorphisms that you get from the option "--def-snps" are the polymorphisms that define the resulting haplogroup, not the snps on the input.

If you need a deeply analysis of the polymorphisms, I recommend you to check https://mseqdr.org "the Mitochondrial Disease Sequence Data Resource Consortium", you will find tools on it that may help you.

Best,

Daniel.

**Comment by nuin** [comment]
Thanks, I have been checking your code, and trying to find the best option to align NCBI genomes to the rCRS. I think the best option would be to use Blast and get the polymorphic sites from a table result. 

I will close the issue and will add any questions I have on new "issues".
